VS-2645 - tablet self-frame and in-focus
molnartimi/jitsi-meet pull request #76
Opened 2021-03-05 17:29 UTC by bekand

2021-03-05 17:36 UTC, vetrabmercedes approved these changes

2021-03-08 10:40 UTC, vetrabmercedes approved these changes

2021-03-08 10:43 UTC, bruderbarna requested changes

2021-03-08 10:43 UTC, bruderbarna commented on package.json
> +    "react-native-device-info": "^8.0.2",
There is no change in package-lock.json, but there should be changes because of this added dependency. Please run npm install and commit the changes

2021-03-08 14:08 UTC, molnartimi approved these changes

2021-03-08 14:08 UTC, kecskesk approved these changes

2021-03-08 14:09 UTC, bruderbarna approved these changes

2021-03-08 14:30 UTC, merged